afternoon_activity/urls.py
from django.urls import path

from . import views

app_name = "afternoon_activity"
urlpatterns = [
    path("", views.homepage, name="homepage"),
    
    path("<int:session_id>/", views.activity_selection, name="activity_selection"),
     
    path("<int:session_id>/<int:activityPK>/cabins/<int:start_cabin_id>-<int:end_cabin_id>/", views.cabins , name="cabins"), # return a list of cabins from start_cabin_id to end_cabin_id 
    path("<int:session_id>/<int:activityPK>/cabins/<int:start_cabin_id>/", views.cabins , name="cabins"), # return that 1 cabin, start_cabin_id
    path("<int:session_id>/<int:activityPK>/cabins/", views.cabins , name="cabins"), # return all cabins for that session_id
    
    path("<int:session_id>/<int:activityPK>/cabin/<int:cabin_id>/", views.cabin , name="cabin"),
    
    path("<int:session_id>/<int:activityPK>/activity-sheet/", views.activity_sheet, name="activity_sheet"),
    
    
    path('<int:activityPK>/<str:activity_date>/', views.activity_pdf_view, name='activity_pdf'),
]

afternoon_activity/templates/afternoon_activity/activity_selection.html
{% extends './base/base.html' %}
{% load custom_filters %}
{% load static %}

{% block title %}
  Activity Selection
{% endblock %}

{% block main_content %}
  <h1>Select the activity you would like to enroll in</h1>
  <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 justify-content-center align-items-center">
    {% for activity in activity_types %}
      {% with image_static='afternoon_activity/img/activity/'|concat:activity.period|concat:'.webp' %}
        <div class="col mb-4 justify-content-center">
          <div class="card shadow border border-dark bg-light">
            <img src="{% static image_static %}" class="card-img-top" alt="session_{{ session.session_number }}.webp" />
            <div class="card-body">
              <h5 class="card-title">{{ activity }}</h5>
              <a href="{% url 'afternoon_activity:cabins' session_id=session.session_number activityPK=activity.pk %}" class="btn btn-primary">Select {{ activity }}</a>
              <ul class="list-group list-group-flush">
                <li class="list-group-item bg-light"></li>
                <li class="list-group-item bg-light" style="padding-top: 20px; padding-bottom: 20px;">
                  <a href="{% url 'afternoon_activity:cabins' session_id=session.session_number activityPK=activity.pk start_cabin_id=10 end_cabin_id=20 %}" class="btn btn-secondary btn-sm">Male Cabin</a>
                </li>
                <li class="list-group-item bg-light" style="padding-top: 20px; padding-bottom: 20px;">
                  <a href="{% url 'afternoon_activity:cabins' session_id=session.session_number activityPK=activity.pk start_cabin_id=0 end_cabin_id=10 %}" class="btn btn-secondary btn-sm">Femamle Cabin</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      {% endwith %}
    {% endfor %}
    
  </div>
{% endblock %}

afternoon_activity/templates/afternoon_activity/activity_sheet.html
{% extends './base/base.html' %}
{% block title %}
  {{ period }} Camper List
{% endblock %}
{% block main_content %}
  <div>
    <h1 class="text-danger">{{ period }} Camper List</h1>
    <form method="post" action="{% url 'afternoon_activity:activity_sheet' session_id=url_session_number activityPK=url_activityPK %}">
      {% csrf_token %}
      <label for="activity-date">Select date:</label>
      <input type="date" id="activity-date" name="activity-date" value="{{ current_date }}" />
      <button type="submit" class="btn btn-primary btn-sm">Update List</button>
    </form>
      <form method="get" action="{% url 'afternoon_activity:activity_pdf' activityPK=url_activityPK activity_date=selected_date %}">
        <button type="submit" class="btn btn-secondary">Generate PDF</button>
    </form>
    <div class="alert alert-light" style="margin-top: 10px;" role="alert">
      Current date is <strong>{{ selected_date }}</strong>
    </div>
    {% for activity in activities %}
      <h1>{{ activity.activity }}</h1>
      <table class="table table-striped table-primary text-center">
        <thead>
          <tr>
            <th>Cabin</th>
            <th>Camper</th>
          </tr>
        </thead>
        <tbody>
          {% for camper in activity.campers.all %}
            <tr>
              <td>
                {% for cabin in camper.session_cabin.all %}
                  {{ cabin.cabin.cabin_number }}{% if not forloop.last %}, {% endif %}
                {% endfor %}
              </td>
              <td>{{ camper.first_name }} {{ camper.last_name }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    {% endfor %}

    {% for activity in rainy_day_activities %}
      <h1>{{ activity.activity }}</h1>
      <table class="table table-striped table-primary text-center table-secondary">
        <thead>
          <tr>
            <th>Cabin</th>
            <th>Camper</th>
          </tr>
        </thead>
        <tbody>
          {% for camper in activity.campers.all %}
            <tr>
              <td>
                {% for cabin in camper.session_cabin.all %}
                  {{ cabin.cabin.cabin_number }}{% if not forloop.last %}, {% endif %}
                {% endfor %}
              </td>
              <td>{{ camper.first_name }} {{ camper.last_name }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    {% endfor %}
  </div>
{% endblock %}

afternoon_activity/templates/afternoon_activity/cabin.html
{% extends './base/base.html' %}
{% load static %}
{% load custom_filters %}


{% block title %}
{{ selected_activity.period }} Cabin: {{cabin_id}}
{% endblock %}

{% block main_content %}
  <h1 class="text-danger">{{ selected_activity.period }} Selection</h1>
  <div class="container text-center">
    <div class="row">
      {% comment %}Left Side{% endcomment %}
      <div class="col col-8">
        <div class="row">
            <div class="col-md-6">
                <div class="weather-widget" style="padding-bottom: 10px;">
                  <h3>Tomorrow's Weather</h3>
                    <img src="http://openweathermap.org/img/wn/{{ tomorrows_icon }}.png" alt="{{ tomorrows_description }}">
                    <div class="weather-info">
                        <h4 class="temperature">{{ tomorrows_weather }} °C</h4>
                        <span class="description">{{ tomorrows_description }};</span>
                        <span class="rain-chance">Chance of rain: {{ tomorrows_rain }}%</span>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
              <h5>
                <label for="activity-date">Select date:</label></h5>
                <form method="post">
                    <input type="date" id="activity-date" name="activity-date" />
                    {% csrf_token %}
                    <button type="submit" class="btn btn-secondary btn-sm">Update Activities</button>
                <div class="alert alert-light" style="margin-top: 10px;" role="alert">Current date is <strong>{{ activity_date }}</strong></div>
            </div>
        </div>
        <table class="table table-striped table-primary">
          <thead>
            <tr>
              {% comment %} <th>Cabin #</th> {% endcomment %}
              <th>Camper</th>
              <th>{{ selected_activity.period }}</th>
              
              {% if selected_activity.period in periods %}
              <th>Rainy Day Activity</th>
              {% endif %}
            
              <th>Submit</th>
            </tr>
          </thead>
          <tbody>
            <form method="post" >
              {% comment %} action="{% url 'afternoon_activity:processing' session_id=session_id activityPK=activityPK cabin_id=cabin_id %}" {% endcomment %}
              {% csrf_token %}
              {% for camper in campers_in_cabin_x %}
                <tr>
                  {% comment %} <td>{{ cabin.cabin_number }}</td> {% endcomment %}
                  <td>{{ camper.first_name }} {{ camper.last_name }}</td>
                  <td>
                    <select class="form-select" data-camper-id="{{ camper.id }}" name="activity_id_{{ camper.id }}">
                      <option selected disabled hidden>🏕️ Choose Activity</option>
                      {% for activity in main_activities %}
                        <option value="{{ activity.id }}">{{ activity.activity }}</option>
                      {% endfor %}
                    </select>
                  </td>
                  {% if selected_activity.period in periods %}
                  <td>
                    <select class="form-select" data-camper-id="{{ camper.id }}" name="rainy_day_activity_id_{{ camper.id }}">
                      <option selected disabled hidden>🌧️ Choose Rainy Day</option>
                      {% for rainy_day_activity in rainy_day_activities %}
                        <option value="{{ rainy_day_activity.id }}">{{ rainy_day_activity.activity }}</option>
                      {% endfor %}
                    </select>
                  </td>
                  {% endif %}
                  <td>
                    <input type="hidden" name="camper_id_{{ camper.id }}" value="{{ camper.id }}" />
                    <button type="submit" id="submit_one_camper-{{camper.id}}" name="submit_one_camper" value="{{ camper.id }}" class="btn btn-warning submit_one_camper">Submit {{ camper.first_name }}</button>                  </td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
              <button type="submit" id="submit_all_campers" name="submit_all_campers" class="btn btn-primary btn-lg submit_all_campers">Submit All</button>
            </form>
      </div>
      {% comment %}Right Side{% endcomment %}
      <div class="col col-4">
        <table class="table table-striped table-primary text-center">
          <thead>
            <tr>
              <th>Activity</th>
              <th>Spots Remaining</th>
              <th>Live Spots Remaining</th>
            </tr>
          </thead>
          <tbody>
            {% for activity in main_activities %}
              <tr id="activity-row-{{ activity.id }}">
                <td>{{ activity.activity }}</td>
                <td>{{ activity.spots_left }}</td>
                <td id="spots-left-{{ activity.id }}">{{ activity.spots_left }}</td>
              </tr>
            {% endfor %}
          </tbody>
          {% if selected_activity.period in periods %}
          <tbody class="table-warning">
            {% for rainy_day_activity in rainy_day_activities %}
              <tr id="activity-row-rainy-day-{{ rainy_day_activity.id }}">
                <td>{{ rainy_day_activity.activity }}</td>
                <td>{{ rainy_day_activity.spots_left }}</td>
                <td id="spots-left-rainy-day-{{ rainy_day_activity.id }}">{{ rainy_day_activity.spots_left }}</td>
              </tr>
            {% endfor %}
            {% endif %}
          </tbody>
        </table>          
        <h5 class="text-secondary text-center">Current Camper Activities</h5>
        <table class="table table-striped table-primary text-center">
          <thead>
              <tr>
                  <th>Camper</th>
                  <th>Main Activity</th>
                  {% if selected_activity.period in periods %}
                  <th>Rainy Day Activity</th>
                  {% endif %}
              </tr>
          </thead>
          <tbody>
              {% for camper in campers_in_cabin_x %}
                  <tr>
                      <td>{{ camper.first_name }} {{ camper.last_name }}</td>
                      <td>
                        {% with camper.camper_in_activity|filter_by_date:activity_date as activity_signed_up_for %}
                        {% with activity_signed_up_for|filter_by_rainy:False as activity_signed_up_for_no_rain %}
                        {% with activity_signed_up_for|filter_by_rainy:True as activity_signed_up_for_with_rain %}

                        
                        {% if activity_signed_up_for_no_rain %}
                        {% for camper_activity_no_rain in activity_signed_up_for_no_rain %}
                        {{ camper_activity_no_rain.activity }}
                        {% endfor %}
                        {% else %}
                              None
                          {% endif %}
                      </td>
                      {% if selected_activity.period in periods %}
                      <td>
                        {% if activity_signed_up_for_with_rain %}
                        {% for camper_activity_rain in activity_signed_up_for_with_rain %}
                        {{ camper_activity_rain.activity }}
                        {%endfor%}                        
                        {% else %}
                              None
                          {% endif %}
                      </td>
                      {% endif %}
                      {% endwith %}
                      {% endwith %}
                      {% endwith %}
                  </tr>
              {% endfor %}
          </tbody>
      </table>  
       </div>
    </div>
  </div>
{% endblock %}
{% block scripts %}
  <script src="{% static 'afternoon_activity/node_modules/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
  <script>
    document.addEventListener('DOMContentLoaded', (event) => {
      document.getElementById('activity-date').value = "{{ activity_date|date:'Y-m-d' }}";
      })

    var activityDropdowns = document.querySelectorAll('.form-select[name^="activity_id_"]');
    var rainyDayActivityDropdowns = document.querySelectorAll('.form-select[name^="rainy_day_activity_id_"]');
    var submitCamperButtons = document.querySelectorAll('.submit_one_camper'); // change 'submit_one_camper' to the class you use
    var submitAll = document.getElementById('submit_all_campers');

    function updateSpotsLeft(dropdown, prefix, camperId) {
      let previousOption = dropdown.options[dropdown.selectedIndex]; // Keep track of the previously selected option
    
      dropdown.addEventListener('change', function() {
        // Increase spots left for the previously selected option by 1
        if (previousOption.value && !previousOption.disabled) {
          let previousActivityId = previousOption.value;
          let previousSpotsLeftCell = document.getElementById('spots-left-' + prefix + previousActivityId);
          let previousSpotsLeft = parseInt(previousSpotsLeftCell.textContent);
          previousSpotsLeftCell.textContent = previousSpotsLeft + 1;
    
          // Enable the submit button if spots left are more than 0
          if (previousSpotsLeft + 1 >= 0) {
            let submitButton = document.getElementById('submit_one_camper-' + camperId);
            submitButton.disabled = false;
            submitAll.disabled = false;

          }
        }
    
        // Decrease spots left for the newly selected option by 1
        let selectedOption = this.options[this.selectedIndex];
        if (!selectedOption.disabled) {
          let activityId = selectedOption.value;
          let spotsLeftCell = document.getElementById('spots-left-' + prefix + activityId);
          let spotsLeft = parseInt(spotsLeftCell.textContent);
          spotsLeftCell.textContent = spotsLeft - 1;
    
          // Disable the submit button if spots left are less than 0
          if (spotsLeft - 1 < 0) {
            let submitButton = document.getElementById('submit_one_camper-' + camperId);
            submitButton.disabled = true;
            submitAll.disabled = true;
          }
        }
    
        // Update the previously selected option
        previousOption = selectedOption;
      });
    }
    activityDropdowns.forEach(function(dropdown) {
      let camperId = dropdown.getAttribute('data-camper-id'); // Assuming you've added a 'data-camper-id' attribute to your dropdowns
      updateSpotsLeft(dropdown, '', camperId);
    });
    
    rainyDayActivityDropdowns.forEach(function(dropdown) {
      let camperId = dropdown.getAttribute('data-camper-id'); // Assuming you've added a 'data-camper-id' attribute to your dropdowns
      updateSpotsLeft(dropdown, 'rainy-day-', camperId);
    });
  </script>
{% endblock %}

afternoon_activity/templates/afternoon_activity/cabins.html
{% extends './base/base.html' %}
{% block title %}
{{ selected_activity.period }} Cabins
{% endblock %}
{% block main_content %}
  <div class="text-center">
    <a class="link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover link-danger" href="{% url 'afternoon_activity:activity_sheet' session_id=url_session_number activityPK=activityPK %}">
      <h1 class="text-danger">{{ selected_activity.period }}</h1>
    </a>
    
    <h2>Cabins</h2>

    {% if activityPK not in activity_type_pks %}
      <div class="alert alert-warning" role="alert">It seems that the activity type ex:(First periord, second periord) does not exist!</div>
      <p>
        <a class="btn btn-link" href="{% url 'afternoon_activity:activity_selection' session_id=url_session_number %}">If you would like to view all activity types click here</a>
      </p>
    {% elif not list_of_cabins %}
      <div class="alert alert-warning" role="alert">It seems that the cabin you have entered does not exist!</div>
      <p>
        <a class="btn btn-link" href="{% url 'afternoon_activity:cabins' session_id=url_session_number activityPK=activityPK start_cabin_id=1 end_cabin_id=19 %}">If you would like to view all cabins click here</a>
      </p>
    {% else %}
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 justify-content-center">
        {% for cabin in list_of_cabins %}
          <div class="col mb-4 justify-content-center">
            <div class="card shadow border border-dark bg-light">
              <div class="card-body">
                <h5 class="card-title text-secondary">Cabin {{ cabin.cabin_number }}</h5>

                {% for counselor in cabin.counselors %}
                <a href="{% url 'afternoon_activity:cabin' session_id=url_session_number activityPK=activityPK cabin_id=cabin.cabin_number %}" class="btn btn-primary">Select Cabin {{ cabin.cabin_number }}</a>
                  {% if counselor.first_name is None %}

                  {% else %}
                    <p class="card-text fw-medium text-warning">{{ counselor.first_name }} {{ counselor.last_name }}</p>
                  {% endif %}
                {% endfor %}
                {% comment %} <a href="{% url 'afternoon_activity:base' cabin_id=cabin.cabin_number %}" class="btn btn-primary">View Cabin {{ cabin.cabin_number }}</a> {% endcomment %}
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    {% endif %}
  </div>
{% endblock %}
{% comment %} <img src="{% static 'afternoon_activity/img/cabin{{ cabin.cabin_number }}.jpg' %}" class="card-img-top" alt="Cabin 1" /> {% endcomment %}

afternoon_activity/templates/afternoon_activity/homepage.html
{% extends './base/base.html' %}
{% load custom_filters %}
{% load static %}

{% comment %}Same as base but the nav bar does not exist{% endcomment %}

{% block title %}
  Home Page
{% endblock %}

{% block navbar %}
  <div style="padding-bottom: 80px;">
    <nav class="navbar bg-body-tertiary fixed-top">
      <div class="container">
        <a class="navbar-brand order-1" style="padding-right: 40px;"></a>
        <a class="navbar-brand order-1" href="{% url 'afternoon_activity:homepage' %}">
          <img class="navbar-logo" style="width: 50px; height: 50px;" src="{% static 'afternoon_activity/img/Camp-T_logo-rounded.png' %}" alt="Camp Transfiguration Logo" />
          Camp Transfiguration
        </a>
        <a class="navbar-brand order-2">
          <img src="http://openweathermap.org/img/w/{{ weather_icon }}.png" alt="{{ weather_description }}" />
          {{ weather }} °C
        </a>
      </div>
    </nav>
  </div>
{% endblock %}

{% block main_content %}
  <h1>Welcome to the Camp-T staff website</h1>
  <div class="row row-cols-1 row-cols-sm-2 row-cols-md-2 row-cols-lg-2 justify-content-center align-items-center">
    {% for session in sessions %}
      {% with image_static='afternoon_activity/img/sessions/session_'|concat:session.session_number|concat:'.webp' %}
        <div class="col mb-4 justify-content-center">
          <div class="card shadow border border-dark bg-light">
            <img src="{% static image_static %}" class="card-img-top" alt="session_{{ session.session_number }}.webp" />
            <div class="card-body">
              <h5 class="card-title" style="margin-bottom:10px">{{ session }}</h5>
              <a href="{% url 'afternoon_activity:activity_selection' session_id=session.session_number %}" class="btn btn-primary">Select {{ session }}</a> <ul class="list-group list-group-flush" style="margin-top: 10px;">
                <li class="list-group-item bg-light"></li>
                {% for activity in List_of_activities %}
                <li class="list-group-item bg-light" style="padding-top: 20px; padding-bottom: 20px;">
                  <a href="{% url 'afternoon_activity:cabins' session_id=session.session_number activityPK=activity.id %}" class="btn btn-secondary btn-sm">{{activity.period}}</a>
                </li>
              {% endfor %}
              </ul>
            </div>
          </div>
        </div>
      {% endwith %}
    {% endfor %}
  </div>
{% endblock %}

afternoon_activity/templates/afternoon_activity/navbar.html
{% load static %}
<nav class="navbar bg-body-tertiary fixed-top">
  <div class="container">
    <a class="navbar-brand order-1" href="{% url 'afternoon_activity:homepage' %}">
      <img class="navbar-logo" style="width: 50px; height: 50px;" src="{% static 'afternoon_activity/img/Camp-T_logo-rounded.png' %}" alt="Camp Transfiguration Logo" />
      Camp Transfiguration
    </a>
    <a class="navbar-brand order-2">
      <img src="http://openweathermap.org/img/w/{{ weather_icon }}.png" alt="{{ weather_description }}">
      {{ weather }} °C
  </a>    
  <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
    <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
      <div class="offcanvas-header" style="background:#ffffe5">
        <h5 class="offcanvas-title" id="offcanvasNavbarLabel" style="background:#ffffe5">
          <img class="navbar-logo" style="width: 50px; height: 50px;" src="{% static 'afternoon_activity/img/Camp-T_logo-rounded.png' %}" alt="Camp Transfiguration Logo" />
          Camp Transfiguration
        </h5>
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body bg-light">
        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'afternoon_activity:homepage' %}">Home</a>
          </li>
          
          {% for activity in  activity_types %}
          <li class="nav-item">
            
            {% comment %}
              !!!!!!!! BASE MODEL WILL ONLY WORK IF YOU HAVE THE SESSION ID !!!!!!
              !!!!!!!! OVERRIDE THE BASE MODEL'S NAV IN YOUR NEW TEMPLATE THAT YOU ARE CREATING TO PREVENT GETTING THIS ERROR.!!!!!!
            {% endcomment %}
            <a class="nav-link active" aria-current="page" href="{% url 'afternoon_activity:cabins' session_id=url_session_number activityPK=activity.pk %}">{{activity}}</a>
          </li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
</nav>

afternoon_activity/templates/afternoon_activity/pdf_template.html
{% for activity in activities %}
  <div style="page-break-after: always;">
    <h1>{{ activity.activity }}</h1>
    <table>
      <tr>
        <th>Cabin</th>
        <th>Camper</th>
      </tr>
      {% for camper in activity.campers.all %}
        <tr>
          <td>
            {% for cabin in camper.session_cabin.all %}
              {{ cabin.cabin.cabin_number }}{% if not forloop.last %}, {% endif %}
            {% endfor %}
          </td>
          <td>{{ camper.first_name }} {{ camper.last_name }}</td>
        </tr>
      {% endfor %}
    </table>
  </div>
{% endfor %}

{% for activity in rainy_day_activities %}
  <div style="page-break-after: always;">
    <h1>{{ activity.activity }}</h1>
    <table>
      <tr>
        <th>Cabin</th>
        <th>Camper</th>
      </tr>
      {% for camper in activity.campers.all %}
        <tr>
          <td>
            {% for cabin in camper.session_cabin.all %}
              {{ cabin.cabin.cabin_number }}{% if not forloop.last %}, {% endif %}
            {% endfor %}
          </td>
          <td>{{ camper.first_name }} {{ camper.last_name }}</td>
        </tr>
      {% endfor %}
    </table>
  </div>
{% endfor %}